### ISSUE TITLE
Install Instructions fail

### ISSUE THREAD

**Issue by MarquisT** [Organice/django-organice#12]
I've followed the Readme and Docs install instructions but they end with errors. 

 
raise ImproperlyConfigured('%s cannot be imported' % model_path)
django.core.exceptions.ImproperlyConfigured: cmsplugin_zinnia.placeholder.EntryPlaceholder cannot be imported

There seems to be problems with the zinnia and django-cms versions. Ideas?

**Comment by bittner** [comment]
Yes, Zinnia and django CMS are the typical candidates for packages that make backward-incompatible changes, and need special attention. (The packages do a lot, to be fair.)

If you use the documented requirements of the releases (see the "Dependencies" in the [change log](http://docs.organice.io/en/latest/changelog.html), or simply [docs/requirements.txt](https://github.com/Organice/django-organice/blob/master/docs/requirements.txt)) you should get a setup running. That setup will be working albeit maybe be a bit aged.
