### ISSUE TITLE
How far is the mailing list component?

### ISSUE THREAD

**Issue by guettli** [Organice/django-organice#5]
How far is the mailing list component? That's something I would very much like to see.

Will you use any packages from pypi or will you build your own?

If you use packages from pypi: which one?

Thank you.

**Comment by lmchawla** [comment]
Waiting eagerly for the 1.7/1.8 compatible release.

**Comment by bittner** [comment]
Good news! Expect me to get my hands dirty this August and September.

Not sure how much this will affect the mailing list component as such. The plan is to lift Organice onto Django 1.8 and the latest stable django-CMS 3. I also plan to provide the themes based on [Foundation](http://foundation.zurb.com/), either exclusively or alongside [Bootstrap](http://getbootstrap.com/) (on which they are based now).

**Comment by lmchawla** [comment]
I would love to help if you could assign some specific todos

**Comment by bittner** [comment]
There are some Django 1.8 compatibility issues of the Emencia newsletter code. I'll have to create a fork and fix those, or find a fork that works with 1.8 already.

@Imchawla If you want you can try to find out which of the existing forks is the most advanced, the most suited one.
